### ISSUE TITLE
Fine Tuning

### ISSUE THREAD

**Issue by mzahran001** [wasidennis/ObjectFlow#1]
How to fine tune your model?
I don't have sufficient data to retrain your model from scratch.
I want to fine tune your model on my data which has only two classes ?

**Comment by zhangjingling** [comment]
can you tell me 2 qheations? 
1.In the Installation  part ,what is the relation between " Install the attached caffe branch, " and "caffe-cedn-dev folder" .
2. caffe-cedn-dev/examples folder ,I download the code ,but I dot have the examples folder.

**Comment by jian-ke** [comment]
@moh3th1 i think the auther use the pre-trained vgg net. So maybe you need to fine-tune your vgg net first, its easy to fine-tune use caffe.
