### ISSUE TITLE
uncompleted folder 

### ISSUE THREAD

**Issue by zhangjingling** [wasidennis/ObjectFlow#2]
can you tell me 2 questions?
1.In the Installation part ,what is the relation between " Install the attached caffe branch, " and "caffe-cedn-dev folder" .
2. caffe-cedn-dev/examples folder ,I download the code ,but I dot have the examples folder.

**Comment by jian-ke** [comment]
1. the caffe code in caffe-cedn floder may be the the old version of caffe.
2. if you download the lastes caffe, you can find examples folder

**Comment by lynn2liu** [comment]
So should I replace the caffe-cedn folder with the lastest caffe version or just leave it?

**Comment by wasidennis** [comment]
Please use the caffe-cedn version and create the examples folder. We are working on a new version that can adapt to the official caffe version, and will release it soon.
