### ISSUE TITLE
Implement three measures 

### ISSUE THREAD

**Issue by InstantWindy** [wasidennis/ObjectFlow#4]
Hello , how did you calculate the Region Similarity and Contour Accuracy? Thank you!

**Comment by wasidennis** [comment]
@InstantWindy do you mean the metric on the DAVIS benchmark? If so, please directly use their provided code for evaluation: https://davischallenge.org/davis2016/code.html.

**Comment by InstantWindy** [comment]
@wasidennis  sorry , but I have a question about the official code "jaccard.py" file and the "f_boundary.py" file.But I don't know what the input parameters of the db_eval_iou function of the'jaccard.py'file and 'db_eval_boundary' function of the 'f_boundary.py' file should be? I don't know what the parameters of these two functions should be. I hope to get your help.Thank you!
